-- Builds dist/install.lua: one self-contained file with every /fleet file inside.
--   lua5.2 tools/build.lua            (write dist/install.lua)
--   lua5.2 tools/build.lua --check    (exit 1 if dist/install.lua is out of date)
-- Upload dist/install.lua to pastebin, then in game:  pastebin run <code>

local SRC = "src/fleet"
local OUT = "dist/install.lua"

local sha2 = dofile(SRC .. "/lib/sha2.lua")
local ser = dofile(SRC .. "/lib/ser.lua")

local function list(dir)
  local out = {}
  local p = io.popen('cd "' .. dir .. '" && find . -type f | sort')
  for line in p:lines() do out[#out + 1] = line:sub(3) end
  p:close()
  return out
end

local function read(path)
  local f = assert(io.open(path, "rb"))
  local s = f:read("*a")
  f:close()
  return s
end

local function longString(s)
  local level = 0
  while s:find("]" .. string.rep("=", level) .. "]", 1, true) do level = level + 1 end
  local eq = string.rep("=", level)
  return "[" .. eq .. "[\n" .. s .. "]" .. eq .. "]"
end

local files, hashes, lines = {}, {}, {}
for _, rel in ipairs(list(SRC)) do
  local data = read(SRC .. "/" .. rel)
  assert(not data:find("\r"), rel .. " has CR line endings")
  files[#files + 1] = { rel, data }
  hashes[rel] = sha2.sha256Hex(data)
  lines[#lines + 1] = rel .. "=" .. hashes[rel]
end
table.sort(lines)
local ver = sha2.sha256Hex(table.concat(lines, "\n")):sub(1, 8)
local manifest = ser.serialize({ files = hashes, ver = ver })

local out = {}
out[#out + 1] = ([[
-- TurtleGPS installer, code version %s (generated by tools/build.lua; do not edit)
-- Installs to /fleet, keeps /fleet/config.lua and /fleet/data, then runs setup if needed.
-- Usage: install [role] [join code] [key=value ...] [-y]   (arguments are passed to setup)
local VERSION = %q
local MANIFEST = %s
local FILES = {}
]]):format(ver, ver, longString(manifest))
for _, f in ipairs(files) do
  out[#out + 1] = ("FILES[%q] = %s\n"):format(f[1], longString(f[2]))
end
out[#out + 1] = [[

local function isCode(rel)
  return not (rel == "config.lua" or rel == "manifest" or rel:sub(1, 5) == "data/" or rel:find("%.tmp$"))
end

local function walk(dir, rel, out)
  for _, name in ipairs(fs.list(dir)) do
    local full, r = fs.combine(dir, name), rel == "" and name or (rel .. "/" .. name)
    if fs.isDir(full) then walk(full, r, out) elseif isCode(r) then out[#out + 1] = r end
  end
  return out
end

print("Installing TurtleGPS " .. VERSION .. " ...")
if fs.exists("/fleet") then
  for _, rel in ipairs(walk("/fleet", "", {})) do
    if not FILES[rel] then fs.delete(fs.combine("/fleet", rel)) end
  end
end
local n = 0
for rel, data in pairs(FILES) do
  local path = fs.combine("/fleet", rel)
  local dir = fs.getDir(path)
  if dir ~= "" and not fs.exists(dir) then fs.makeDir(dir) end
  local h = fs.open(path, "w")
  h.write(data)
  h.close()
  n = n + 1
end
local h = fs.open("/fleet/manifest", "w")
h.write(MANIFEST)
h.close()
if not fs.exists("/fleet/data") then fs.makeDir("/fleet/data") end
print("Wrote " .. n .. " files to /fleet")

-- arguments go to setup:  pastebin run <code> turtle TG-7-...-1f2e
local args = { ... }
if fs.exists("/fleet/config.lua") and #args == 0 then
  local startup = 'shell.run("/fleet/boot.lua")\n'
  local sh = fs.open("/startup.lua", "w")
  sh.write(startup)
  sh.close()
  print("Existing config kept. Rebooting...")
  sleep(1)
  os.reboot()
else
  shell.run("/fleet/bin/setup.lua", table.unpack(args))
end
]]

local text = table.concat(out)
if arg[1] == "--check" then
  local f = io.open(OUT, "rb")
  local cur = f and f:read("*a")
  if f then f:close() end
  if cur ~= text then
    io.stderr:write(OUT .. " is out of date: run lua5.2 tools/build.lua\n")
    os.exit(1)
  end
  print(OUT .. " is up to date (" .. ver .. ")")
else
  local f = assert(io.open(OUT, "wb"))
  f:write(text)
  f:close()
  print(("%s: %d files, %d bytes, version %s"):format(OUT, #files, #text, ver))
end
